if (WIN32 OR MSYS)
    set (CMAKE_GENERATOR "MSYS Makefiles" CACHE INTERNAL "" FORCE)
    message(STATUS "==> Generating MSYS Makefiles")
        elseif(UNIX)
            set (CMAKE_GENERATOR "Unix Makefiles" CACHE INTERNAL "" FORCE)
            message(STATUS "==> Generating Generating Unix Makefiles")
        else()
            message(FATAL_ERROR "==> This projet buildable only Windows MSYS or Unix/Linux os.")
endif()